// <auto-generated />
using Heimdall.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Heimdall.Data.Migrations
{
    [DbContext(typeof(WorkInstructionDatabaseContext))]
    [Migration("20230301195455_secondmigration")]
    partial class secondmigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Heimdall.Logic.WorkInstructions.Entities.Instruction", b =>
                {
                    b.Property<int>("InstructionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("InstructionId"));

                    b.Property<string>("InstructionCordinates")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("InstructionForeignKey")
                        .HasColumnType("integer");

                    b.Property<string>("InstructionImage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("InstructionText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("InstructionId");

                    b.HasIndex("InstructionForeignKey");

                    b.ToTable("Instructions");
                });

            modelBuilder.Entity("Heimdall.Logic.WorkInstructions.Entities.WorkInstruction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("WorkInstructions");
                });

            modelBuilder.Entity("Heimdall.Logic.WorkInstructions.Entities.Instruction", b =>
                {
                    b.HasOne("Heimdall.Logic.WorkInstructions.Entities.WorkInstruction", null)
                        .WithMany("InstructionList")
                        .HasForeignKey("InstructionForeignKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Heimdall.Logic.WorkInstructions.Entities.WorkInstruction", b =>
                {
                    b.Navigation("InstructionList");
                });
#pragma warning restore 612, 618
        }
    }
}
